homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('my_story/', views.my_story, name='my_story'),
    path('jadwalku/', views.jadwalku, name='jadwalku'),
    path('delete/<id>', views.delete, name='delete')

    # dilanjutkan ...
]

mydjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),

]

homepage/models.py
from django.db import models

# Create your models here.

class jadwalkua(models.Model):
    # Fields
    date_field = models.DateField()
    activity_field = models.CharField(max_length=50)
    venue_field = models.CharField(max_length=50)
    category_field = models.CharField(max_length=50)

    # Methods
    
    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.activity_field

homepage/forms.py
from django import forms
from .models import jadwalkua


class UserModelForm(forms.ModelForm):
    class Meta:
        model = jadwalkua
        fields = '__all__'

homepage/views.py
from django.shortcuts import render
from .forms import UserModelForm
from .models import jadwalkua
from django.http import HttpResponseRedirect

# Create your views here.
def index(request):
    return render(request, 'index.html')

def my_story(request):
	return render(request, 'my_story.html')

def jadwalku(request):
    data = jadwalkua.objects.all()
    context = {}
    if request.method == 'POST':
        
        form = UserModelForm(request.POST or None)
        if form.is_valid():
            form.save()
            form = UserModelForm()
            return HttpResponseRedirect('/jadwalku/')
    else:
        form = UserModelForm()


    return render(request, 'jadwalku.html',{'form': form,"data":data})

def delete(request, id):
    data = jadwalkua.objects.get(id=id)
    data.delete()
    return HttpResponseRedirect('/jadwalku/')

homepage/templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/Story3.css' %}">

<title>Mario Ekaputta</title>
  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'homepage:index' %}"><div class="box">Home</div></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#about"><div class="box">About Me</div></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#backgrounds"><div class="box">Background</div></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#contact"><div class="box">Contact Me</div></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'homepage:my_story' %}"><div class="box">My Story</div></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'homepage:jadwalku' %}"><div class="box">My Schedule</div></a>
        </li>
      </ul>
    </div>
  </nav>

<header class="page-header header container-fluid">
  <h1>Mario Ekaputta</h1>
  <p>Profesional Bio</br>Welcome to my website</p>
</header>

<div id="about" class="about_me">
  <h2>-Mario Ekaputta-</h2>
  </br>
  </br>	
  <img src = "{% static 'images/Foto.jpg' %}" width="250" height="250">
  </br>
  </br>
  </br>
  <h2>Description</h2>
  <p> Mario is a second year student majoring in Computer Science at Faculty of Computer Science in Universitas Indonesia. He was born at 2nd of January 2001 in Jakarta. His ambition is to be a successful enterpreneur and to travel the world with his family.</p>
</div>

<div id="backgrounds" class="Background" style="background-color: #C0C0C0">
	<h3>Education</h3>
	<p> Mutiara Bangsa School (2003-2018)</br>Universitas Indonesia (2018-Present)
	</p>
	</br>
	<h3>Skills</h3>
	<p>Public Speaking </br>Decision Making</br>Leadership</br>Web Design</p>
	</br>
	<h3>Achievements</h3>
	<p>Best Graduate Students of Mutiara Bangsa School 2018</br>Top 8 Bussiness Case Competition at Tarumanegara University</p>
	</br>
	<h3>Experience</h3>
	<p>PIC of Competition 31st Annual of Vesakh KMBUI</br>Staff Startup Academy Compfest XI</br>PIC of Liaision Officer Faculty of Computer Science Graduation Ceremony 2019</p>
</div>

<div id="contact" class="Contact" style="text-align: left;">
	<h4>Contact Me</h4>
	<p>   <img src="{% static 'images/wa.png' %}" width="50" height="50">	+62 851 0675 9918</p>
	<p>   <img src="{% static 'images/line.jpg' %}" width="50" height="50">	Mario_721</p>
	<p>   <img src="{% static 'images/instagram.jpg' %}" width="50" height="50">	@marioekaputta</p>
</div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="main.js"></script>
  </body>
</html>

homepage/templates/jadwalku.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/Story3.css' %}">

<title>Mario Ekaputta</title>
  </head>
  <body>
<nav class="navbar navbar-expand-md fixed-top">
  <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#main-navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="main-navigation">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:index' %}"><div class="box">Back to Home</div></a>
      </li>	
    </ul>
  </div>
</nav>


<div class="jadwalku"style="margin-top:100px">

 <form method='POST' > 
 {% csrf_token %}
                {{ form.as_p }}
                <input type='submit' value='Save' />
            </form>



</div>

    <div id="section2" style="height: auto">
        <h1>Schedule :</h1>
        <ol>
            {% for i in data %}
            <li>Date : {{i.date_field}} <br>
                Activity : {{i.activity_field}} <br>
                Place : {{i.venue_field}} <br>
                Category : {{i.category_field}} <br>
                <a href="{% url 'homepage:delete' id=i.id %}"><button type="submit" style="margin-bottom: 15px">Delete</button></a>
                <br>
            </li>
            {% endfor %}
        </ol>
    </div>

homepage/templates/my_story.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/Story3.css' %}">

<title>Mario Ekaputta</title>
  </head>
  <body>
<nav class="navbar navbar-expand-md fixed-top">
  <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#main-navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="main-navigation">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'homepage:index' %}"><div class="box">Back to Home</div></a>
      </li>	
    </ul>
  </div>
</nav>


<div class="my_story">
  <h1>UI Students</h1>
  <p>July 3rd, 2018, I become a student of Universitas Indonesia. That was such an amazing achievement for me knowing what I’ve been dreaming for the last 12 months. When everyone knows about my ambition to be a student of one of the best college in Indonesia, most of them laugh. Well, I’m not a very good student. My teacher knows me as the laziest student in the class. But, I have a vision. Once I have a vision and with all complement and insult as my motivation. I did it. </p>
</div>